(define (problem drone_problem_d2_r2_l9_p9_c9_g9_ct2)
  (:domain drone-domain)
  (:objects
    dron1 - dron
    dron2 - dron
    carrier1 - transportador
    carrier2 - transportador
    deposito - location
    loc1 - location
    loc2 - location
    loc3 - location
    loc4 - location
    loc5 - location
    loc6 - location
    loc7 - location
    loc8 - location
    loc9 - location
    crate1 - caja
    crate2 - caja
    crate3 - caja
    crate4 - caja
    crate5 - caja
    crate6 - caja
    crate7 - caja
    crate8 - caja
    crate9 - caja
    comida - content
    medicina - content
    person1 - person
    person2 - person
    person3 - person
    person4 - person
    person5 - person
    person6 - person
    person7 - person
    person8 - person
    person9 - person
    n0 - num
    n1 - num
    n2 - num
    n3 - num
    n4 - num
  )

  (:init
    (at dron1 deposito)
    (at dron2 deposito)
    (at carrier1 deposito)
    (at carrier2 deposito)
    (at crate1 deposito)
    (at crate2 deposito)
    (at crate3 deposito)
    (at crate4 deposito)
    (at crate5 deposito)
    (at crate6 deposito)
    (at crate7 deposito)
    (at crate8 deposito)
    (at crate9 deposito)
    (contenido-caja crate1 comida)
    (contenido-caja crate2 medicina)
    (contenido-caja crate3 medicina)
    (contenido-caja crate4 medicina)
    (contenido-caja crate5 medicina)
    (contenido-caja crate6 medicina)
    (contenido-caja crate7 medicina)
    (contenido-caja crate8 medicina)
    (contenido-caja crate9 medicina)
    (at person1 loc2)
    (at person2 loc2)
    (at person3 loc2)
    (at person4 loc1)
    (at person5 loc4)
    (at person6 loc2)
    (at person7 loc9)
    (at person8 loc4)
    (at person9 loc8)
    (person-needs person1 medicina)
    (person-needs person2 medicina)
    (person-needs person3 medicina)
    (person-needs person4 medicina)
    (person-needs person5 comida)
    (person-needs person5 medicina)
    (person-needs person6 medicina)
    (person-needs person7 medicina)
    (person-needs person9 medicina)
    (brazo-libre dron1)
    (dron-libre dron1)
    (brazo-libre dron2)
    (dron-libre dron2)
    (siguiente-t carrier1 n0 n1)
    (siguiente-t carrier1 n1 n2)
    (siguiente-t carrier1 n2 n3)
    (siguiente-t carrier1 n3 n4)
    (cajas-en carrier1 n0)
    (siguiente-t carrier2 n0 n1)
    (siguiente-t carrier2 n1 n2)
    (siguiente-t carrier2 n2 n3)
    (siguiente-t carrier2 n3 n4)
    (cajas-en carrier2 n0)
    (caja-libre crate1)
    (caja-libre crate2)
    (caja-libre crate3)
    (caja-libre crate4)
    (caja-libre crate5)
    (caja-libre crate6)
    (caja-libre crate7)
    (caja-libre crate8)
    (caja-libre crate9)
    (persona-libre person1)
    (persona-libre person2)
    (persona-libre person3)
    (persona-libre person4)
    (persona-libre person5)
    (persona-libre person6)
    (persona-libre person7)
    (persona-libre person8)
    (persona-libre person9)
    (transportador-libre carrier1)
    (transportador-libre carrier2)
	(= (fly-cost deposito loc1) 206)
	(= (fly-cost deposito loc2) 145)
	(= (fly-cost deposito loc3) 109)
	(= (fly-cost deposito loc4) 270)
	(= (fly-cost deposito loc5) 221)
	(= (fly-cost deposito loc6) 86)
	(= (fly-cost deposito loc7) 263)
	(= (fly-cost deposito loc8) 238)
	(= (fly-cost deposito loc9) 167)
	(= (fly-cost loc1 deposito) 206)
	(= (fly-cost loc1 loc2) 184)
	(= (fly-cost loc1 loc3) 109)
	(= (fly-cost loc1 loc4) 144)
	(= (fly-cost loc1 loc5) 167)
	(= (fly-cost loc1 loc6) 177)
	(= (fly-cost loc1 loc7) 123)
	(= (fly-cost loc1 loc8) 110)
	(= (fly-cost loc1 loc9) 158)
	(= (fly-cost loc2 deposito) 145)
	(= (fly-cost loc2 loc1) 184)
	(= (fly-cost loc2 loc3) 98)
	(= (fly-cost loc2 loc4) 159)
	(= (fly-cost loc2 loc5) 89)
	(= (fly-cost loc2 loc6) 60)
	(= (fly-cost loc2 loc7) 163)
	(= (fly-cost loc2 loc8) 140)
	(= (fly-cost loc2 loc9) 39)
	(= (fly-cost loc3 deposito) 109)
	(= (fly-cost loc3 loc1) 109)
	(= (fly-cost loc3 loc2) 98)
	(= (fly-cost loc3 loc4) 167)
	(= (fly-cost loc3 loc5) 135)
	(= (fly-cost loc3 loc6) 71)
	(= (fly-cost loc3 loc7) 157)
	(= (fly-cost loc3 loc8) 133)
	(= (fly-cost loc3 loc9) 92)
	(= (fly-cost loc4 deposito) 270)
	(= (fly-cost loc4 loc1) 144)
	(= (fly-cost loc4 loc2) 159)
	(= (fly-cost loc4 loc3) 167)
	(= (fly-cost loc4 loc5) 78)
	(= (fly-cost loc4 loc6) 198)
	(= (fly-cost loc4 loc7) 24)
	(= (fly-cost loc4 loc8) 38)
	(= (fly-cost loc4 loc9) 121)
	(= (fly-cost loc5 deposito) 221)
	(= (fly-cost loc5 loc1) 167)
	(= (fly-cost loc5 loc2) 89)
	(= (fly-cost loc5 loc3) 135)
	(= (fly-cost loc5 loc4) 78)
	(= (fly-cost loc5 loc6) 139)
	(= (fly-cost loc5 loc7) 90)
	(= (fly-cost loc5 loc8) 75)
	(= (fly-cost loc5 loc9) 56)
	(= (fly-cost loc6 deposito) 86)
	(= (fly-cost loc6 loc1) 177)
	(= (fly-cost loc6 loc2) 60)
	(= (fly-cost loc6 loc3) 71)
	(= (fly-cost loc6 loc4) 198)
	(= (fly-cost loc6 loc5) 139)
	(= (fly-cost loc6 loc7) 196)
	(= (fly-cost loc6 loc8) 171)
	(= (fly-cost loc6 loc9) 84)
	(= (fly-cost loc7 deposito) 263)
	(= (fly-cost loc7 loc1) 123)
	(= (fly-cost loc7 loc2) 163)
	(= (fly-cost loc7 loc3) 157)
	(= (fly-cost loc7 loc4) 24)
	(= (fly-cost loc7 loc5) 90)
	(= (fly-cost loc7 loc6) 196)
	(= (fly-cost loc7 loc8) 26)
	(= (fly-cost loc7 loc9) 125)
	(= (fly-cost loc8 deposito) 238)
	(= (fly-cost loc8 loc1) 110)
	(= (fly-cost loc8 loc2) 140)
	(= (fly-cost loc8 loc3) 133)
	(= (fly-cost loc8 loc4) 38)
	(= (fly-cost loc8 loc5) 75)
	(= (fly-cost loc8 loc6) 171)
	(= (fly-cost loc8 loc7) 26)
	(= (fly-cost loc8 loc9) 102)
	(= (fly-cost loc9 deposito) 167)
	(= (fly-cost loc9 loc1) 158)
	(= (fly-cost loc9 loc2) 39)
	(= (fly-cost loc9 loc3) 92)
	(= (fly-cost loc9 loc4) 121)
	(= (fly-cost loc9 loc5) 56)
	(= (fly-cost loc9 loc6) 84)
	(= (fly-cost loc9 loc7) 125)
	(= (fly-cost loc9 loc8) 102)
	(= (fly-cost deposito deposito) 999999)
	(= (fly-cost loc1 loc1) 999999)
	(= (fly-cost loc2 loc2) 999999)
	(= (fly-cost loc3 loc3) 999999)
	(= (fly-cost loc4 loc4) 999999)
	(= (fly-cost loc5 loc5) 999999)
	(= (fly-cost loc6 loc6) 999999)
	(= (fly-cost loc7 loc7) 999999)
	(= (fly-cost loc8 loc8) 999999)
	(= (fly-cost loc9 loc9) 999999)
(= (fly-cost deposito deposito) 999999)
  )

  (:goal (and
    (at dron1 deposito)
    (at dron2 deposito)
    (person-has person1 medicina)
    (person-has person2 medicina)
    (person-has person3 medicina)
    (person-has person4 medicina)
    (person-has person5 comida)
    (person-has person5 medicina)
    (person-has person6 medicina)
    (person-has person7 medicina)
    (person-has person9 medicina)
    (at carrier1 deposito)
    (at carrier2 deposito)
  ))

  (:metric minimize (total-time))
)
