(define (problem drone_problem_d1_r0_l17_p17_c17_g17_ct2)
(:domain drone-domain)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	food - contents
	medicine - contents
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
)
(:init
	(at drone1 depot)
	(arm1-free drone1)
	(arm2-free drone1)
	(at crate1 depot)
	(at crate2 depot)
	(at crate3 depot)
	(at crate4 depot)
	(at crate5 depot)
	(at crate6 depot)
	(at crate7 depot)
	(at crate8 depot)
	(at crate9 depot)
	(at crate10 depot)
	(at crate11 depot)
	(at crate12 depot)
	(at crate13 depot)
	(at crate14 depot)
	(at crate15 depot)
	(at crate16 depot)
	(at crate17 depot)
	(crate-content crate1 food)
	(crate-content crate2 food)
	(crate-content crate3 food)
	(crate-content crate4 food)
	(crate-content crate5 food)
	(crate-content crate6 food)
	(crate-content crate7 food)
	(crate-content crate8 food)
	(crate-content crate9 food)
	(crate-content crate10 food)
	(crate-content crate11 food)
	(crate-content crate12 food)
	(crate-content crate13 food)
	(crate-content crate14 food)
	(crate-content crate15 medicine)
	(crate-content crate16 medicine)
	(crate-content crate17 medicine)
	(at person1 loc8)
	(at person2 loc5)
	(at person3 loc1)
	(at person4 loc12)
	(at person5 loc11)
	(at person6 loc12)
	(at person7 loc14)
	(at person8 loc10)
	(at person9 loc5)
	(at person10 loc10)
	(at person11 loc5)
	(at person12 loc9)
	(at person13 loc14)
	(at person14 loc5)
	(at person15 loc4)
	(at person16 loc3)
	(at person17 loc6)
	(person-needs person1 food)
	(person-needs person3 food)
	(person-needs person4 food)
	(person-needs person4 medicine)
	(person-needs person5 food)
	(person-needs person6 food)
	(person-needs person6 medicine)
	(person-needs person7 food)
	(person-needs person8 food)
	(person-needs person10 food)
	(person-needs person11 food)
	(person-needs person12 food)
	(person-needs person12 medicine)
	(person-needs person13 food)
	(person-needs person14 food)
	(person-needs person15 food)
	(person-needs person16 food)
)
(:goal (and
	(at drone1 depot)
	(person-has person1 food)
	(person-has person3 food)
	(person-has person4 food)
	(person-has person4 medicine)
	(person-has person5 food)
	(person-has person6 food)
	(person-has person6 medicine)
	(person-has person7 food)
	(person-has person8 food)
	(person-has person10 food)
	(person-has person11 food)
	(person-has person12 food)
	(person-has person12 medicine)
	(person-has person13 food)
	(person-has person14 food)
	(person-has person15 food)
	(person-has person16 food)
	))
)
