(define (problem drone_problem_d1_r0_l24_p24_c24_g24_ct2)
(:domain drone-domain)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	food - contents
	medicine - contents
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
)
(:init
	(at drone1 depot)
	(arm1-free drone1)
	(arm2-free drone1)
	(at crate1 depot)
	(at crate2 depot)
	(at crate3 depot)
	(at crate4 depot)
	(at crate5 depot)
	(at crate6 depot)
	(at crate7 depot)
	(at crate8 depot)
	(at crate9 depot)
	(at crate10 depot)
	(at crate11 depot)
	(at crate12 depot)
	(at crate13 depot)
	(at crate14 depot)
	(at crate15 depot)
	(at crate16 depot)
	(at crate17 depot)
	(at crate18 depot)
	(at crate19 depot)
	(at crate20 depot)
	(at crate21 depot)
	(at crate22 depot)
	(at crate23 depot)
	(at crate24 depot)
	(crate-content crate1 food)
	(crate-content crate2 food)
	(crate-content crate3 food)
	(crate-content crate4 food)
	(crate-content crate5 food)
	(crate-content crate6 food)
	(crate-content crate7 food)
	(crate-content crate8 food)
	(crate-content crate9 food)
	(crate-content crate10 medicine)
	(crate-content crate11 medicine)
	(crate-content crate12 medicine)
	(crate-content crate13 medicine)
	(crate-content crate14 medicine)
	(crate-content crate15 medicine)
	(crate-content crate16 medicine)
	(crate-content crate17 medicine)
	(crate-content crate18 medicine)
	(crate-content crate19 medicine)
	(crate-content crate20 medicine)
	(crate-content crate21 medicine)
	(crate-content crate22 medicine)
	(crate-content crate23 medicine)
	(crate-content crate24 medicine)
	(at person1 loc16)
	(at person2 loc17)
	(at person3 loc7)
	(at person4 loc19)
	(at person5 loc4)
	(at person6 loc18)
	(at person7 loc12)
	(at person8 loc21)
	(at person9 loc9)
	(at person10 loc6)
	(at person11 loc18)
	(at person12 loc10)
	(at person13 loc16)
	(at person14 loc12)
	(at person15 loc20)
	(at person16 loc16)
	(at person17 loc5)
	(at person18 loc7)
	(at person19 loc4)
	(at person20 loc20)
	(at person21 loc1)
	(at person22 loc16)
	(at person23 loc16)
	(at person24 loc18)
	(person-needs person1 food)
	(person-needs person2 food)
	(person-needs person3 food)
	(person-needs person3 medicine)
	(person-needs person4 medicine)
	(person-needs person5 medicine)
	(person-needs person6 medicine)
	(person-needs person7 food)
	(person-needs person7 medicine)
	(person-needs person8 food)
	(person-needs person9 medicine)
	(person-needs person10 medicine)
	(person-needs person11 food)
	(person-needs person12 medicine)
	(person-needs person13 food)
	(person-needs person14 medicine)
	(person-needs person16 food)
	(person-needs person16 medicine)
	(person-needs person17 food)
	(person-needs person17 medicine)
	(person-needs person20 medicine)
	(person-needs person21 medicine)
	(person-needs person23 medicine)
	(person-needs person24 medicine)
)
(:goal (and
	(at drone1 depot)
	(person-has person1 food)
	(person-has person2 food)
	(person-has person3 food)
	(person-has person3 medicine)
	(person-has person4 medicine)
	(person-has person5 medicine)
	(person-has person6 medicine)
	(person-has person7 food)
	(person-has person7 medicine)
	(person-has person8 food)
	(person-has person9 medicine)
	(person-has person10 medicine)
	(person-has person11 food)
	(person-has person12 medicine)
	(person-has person13 food)
	(person-has person14 medicine)
	(person-has person16 food)
	(person-has person16 medicine)
	(person-has person17 food)
	(person-has person17 medicine)
	(person-has person20 medicine)
	(person-has person21 medicine)
	(person-has person23 medicine)
	(person-has person24 medicine)
	))
)
