(define (problem drone_problem_d1_r0_l111_p111_c111_g111_ct2)
(:domain drone-domain)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	loc42 - location
	loc43 - location
	loc44 - location
	loc45 - location
	loc46 - location
	loc47 - location
	loc48 - location
	loc49 - location
	loc50 - location
	loc51 - location
	loc52 - location
	loc53 - location
	loc54 - location
	loc55 - location
	loc56 - location
	loc57 - location
	loc58 - location
	loc59 - location
	loc60 - location
	loc61 - location
	loc62 - location
	loc63 - location
	loc64 - location
	loc65 - location
	loc66 - location
	loc67 - location
	loc68 - location
	loc69 - location
	loc70 - location
	loc71 - location
	loc72 - location
	loc73 - location
	loc74 - location
	loc75 - location
	loc76 - location
	loc77 - location
	loc78 - location
	loc79 - location
	loc80 - location
	loc81 - location
	loc82 - location
	loc83 - location
	loc84 - location
	loc85 - location
	loc86 - location
	loc87 - location
	loc88 - location
	loc89 - location
	loc90 - location
	loc91 - location
	loc92 - location
	loc93 - location
	loc94 - location
	loc95 - location
	loc96 - location
	loc97 - location
	loc98 - location
	loc99 - location
	loc100 - location
	loc101 - location
	loc102 - location
	loc103 - location
	loc104 - location
	loc105 - location
	loc106 - location
	loc107 - location
	loc108 - location
	loc109 - location
	loc110 - location
	loc111 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	crate49 - crate
	crate50 - crate
	crate51 - crate
	crate52 - crate
	crate53 - crate
	crate54 - crate
	crate55 - crate
	crate56 - crate
	crate57 - crate
	crate58 - crate
	crate59 - crate
	crate60 - crate
	crate61 - crate
	crate62 - crate
	crate63 - crate
	crate64 - crate
	crate65 - crate
	crate66 - crate
	crate67 - crate
	crate68 - crate
	crate69 - crate
	crate70 - crate
	crate71 - crate
	crate72 - crate
	crate73 - crate
	crate74 - crate
	crate75 - crate
	crate76 - crate
	crate77 - crate
	crate78 - crate
	crate79 - crate
	crate80 - crate
	crate81 - crate
	crate82 - crate
	crate83 - crate
	crate84 - crate
	crate85 - crate
	crate86 - crate
	crate87 - crate
	crate88 - crate
	crate89 - crate
	crate90 - crate
	crate91 - crate
	crate92 - crate
	crate93 - crate
	crate94 - crate
	crate95 - crate
	crate96 - crate
	crate97 - crate
	crate98 - crate
	crate99 - crate
	crate100 - crate
	crate101 - crate
	crate102 - crate
	crate103 - crate
	crate104 - crate
	crate105 - crate
	crate106 - crate
	crate107 - crate
	crate108 - crate
	crate109 - crate
	crate110 - crate
	crate111 - crate
	food - contents
	medicine - contents
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
	person42 - person
	person43 - person
	person44 - person
	person45 - person
	person46 - person
	person47 - person
	person48 - person
	person49 - person
	person50 - person
	person51 - person
	person52 - person
	person53 - person
	person54 - person
	person55 - person
	person56 - person
	person57 - person
	person58 - person
	person59 - person
	person60 - person
	person61 - person
	person62 - person
	person63 - person
	person64 - person
	person65 - person
	person66 - person
	person67 - person
	person68 - person
	person69 - person
	person70 - person
	person71 - person
	person72 - person
	person73 - person
	person74 - person
	person75 - person
	person76 - person
	person77 - person
	person78 - person
	person79 - person
	person80 - person
	person81 - person
	person82 - person
	person83 - person
	person84 - person
	person85 - person
	person86 - person
	person87 - person
	person88 - person
	person89 - person
	person90 - person
	person91 - person
	person92 - person
	person93 - person
	person94 - person
	person95 - person
	person96 - person
	person97 - person
	person98 - person
	person99 - person
	person100 - person
	person101 - person
	person102 - person
	person103 - person
	person104 - person
	person105 - person
	person106 - person
	person107 - person
	person108 - person
	person109 - person
	person110 - person
	person111 - person
)
(:init
	(at drone1 depot)
	(arm1-free drone1)
	(arm2-free drone1)
	(at crate1 depot)
	(at crate2 depot)
	(at crate3 depot)
	(at crate4 depot)
	(at crate5 depot)
	(at crate6 depot)
	(at crate7 depot)
	(at crate8 depot)
	(at crate9 depot)
	(at crate10 depot)
	(at crate11 depot)
	(at crate12 depot)
	(at crate13 depot)
	(at crate14 depot)
	(at crate15 depot)
	(at crate16 depot)
	(at crate17 depot)
	(at crate18 depot)
	(at crate19 depot)
	(at crate20 depot)
	(at crate21 depot)
	(at crate22 depot)
	(at crate23 depot)
	(at crate24 depot)
	(at crate25 depot)
	(at crate26 depot)
	(at crate27 depot)
	(at crate28 depot)
	(at crate29 depot)
	(at crate30 depot)
	(at crate31 depot)
	(at crate32 depot)
	(at crate33 depot)
	(at crate34 depot)
	(at crate35 depot)
	(at crate36 depot)
	(at crate37 depot)
	(at crate38 depot)
	(at crate39 depot)
	(at crate40 depot)
	(at crate41 depot)
	(at crate42 depot)
	(at crate43 depot)
	(at crate44 depot)
	(at crate45 depot)
	(at crate46 depot)
	(at crate47 depot)
	(at crate48 depot)
	(at crate49 depot)
	(at crate50 depot)
	(at crate51 depot)
	(at crate52 depot)
	(at crate53 depot)
	(at crate54 depot)
	(at crate55 depot)
	(at crate56 depot)
	(at crate57 depot)
	(at crate58 depot)
	(at crate59 depot)
	(at crate60 depot)
	(at crate61 depot)
	(at crate62 depot)
	(at crate63 depot)
	(at crate64 depot)
	(at crate65 depot)
	(at crate66 depot)
	(at crate67 depot)
	(at crate68 depot)
	(at crate69 depot)
	(at crate70 depot)
	(at crate71 depot)
	(at crate72 depot)
	(at crate73 depot)
	(at crate74 depot)
	(at crate75 depot)
	(at crate76 depot)
	(at crate77 depot)
	(at crate78 depot)
	(at crate79 depot)
	(at crate80 depot)
	(at crate81 depot)
	(at crate82 depot)
	(at crate83 depot)
	(at crate84 depot)
	(at crate85 depot)
	(at crate86 depot)
	(at crate87 depot)
	(at crate88 depot)
	(at crate89 depot)
	(at crate90 depot)
	(at crate91 depot)
	(at crate92 depot)
	(at crate93 depot)
	(at crate94 depot)
	(at crate95 depot)
	(at crate96 depot)
	(at crate97 depot)
	(at crate98 depot)
	(at crate99 depot)
	(at crate100 depot)
	(at crate101 depot)
	(at crate102 depot)
	(at crate103 depot)
	(at crate104 depot)
	(at crate105 depot)
	(at crate106 depot)
	(at crate107 depot)
	(at crate108 depot)
	(at crate109 depot)
	(at crate110 depot)
	(at crate111 depot)
	(crate-content crate1 food)
	(crate-content crate2 food)
	(crate-content crate3 food)
	(crate-content crate4 food)
	(crate-content crate5 food)
	(crate-content crate6 food)
	(crate-content crate7 food)
	(crate-content crate8 food)
	(crate-content crate9 food)
	(crate-content crate10 food)
	(crate-content crate11 food)
	(crate-content crate12 food)
	(crate-content crate13 food)
	(crate-content crate14 food)
	(crate-content crate15 food)
	(crate-content crate16 food)
	(crate-content crate17 food)
	(crate-content crate18 food)
	(crate-content crate19 food)
	(crate-content crate20 food)
	(crate-content crate21 food)
	(crate-content crate22 food)
	(crate-content crate23 food)
	(crate-content crate24 food)
	(crate-content crate25 food)
	(crate-content crate26 food)
	(crate-content crate27 food)
	(crate-content crate28 food)
	(crate-content crate29 food)
	(crate-content crate30 food)
	(crate-content crate31 food)
	(crate-content crate32 food)
	(crate-content crate33 food)
	(crate-content crate34 food)
	(crate-content crate35 food)
	(crate-content crate36 food)
	(crate-content crate37 food)
	(crate-content crate38 food)
	(crate-content crate39 food)
	(crate-content crate40 food)
	(crate-content crate41 food)
	(crate-content crate42 food)
	(crate-content crate43 food)
	(crate-content crate44 food)
	(crate-content crate45 food)
	(crate-content crate46 food)
	(crate-content crate47 food)
	(crate-content crate48 food)
	(crate-content crate49 food)
	(crate-content crate50 food)
	(crate-content crate51 food)
	(crate-content crate52 food)
	(crate-content crate53 food)
	(crate-content crate54 food)
	(crate-content crate55 food)
	(crate-content crate56 food)
	(crate-content crate57 food)
	(crate-content crate58 food)
	(crate-content crate59 food)
	(crate-content crate60 food)
	(crate-content crate61 food)
	(crate-content crate62 food)
	(crate-content crate63 medicine)
	(crate-content crate64 medicine)
	(crate-content crate65 medicine)
	(crate-content crate66 medicine)
	(crate-content crate67 medicine)
	(crate-content crate68 medicine)
	(crate-content crate69 medicine)
	(crate-content crate70 medicine)
	(crate-content crate71 medicine)
	(crate-content crate72 medicine)
	(crate-content crate73 medicine)
	(crate-content crate74 medicine)
	(crate-content crate75 medicine)
	(crate-content crate76 medicine)
	(crate-content crate77 medicine)
	(crate-content crate78 medicine)
	(crate-content crate79 medicine)
	(crate-content crate80 medicine)
	(crate-content crate81 medicine)
	(crate-content crate82 medicine)
	(crate-content crate83 medicine)
	(crate-content crate84 medicine)
	(crate-content crate85 medicine)
	(crate-content crate86 medicine)
	(crate-content crate87 medicine)
	(crate-content crate88 medicine)
	(crate-content crate89 medicine)
	(crate-content crate90 medicine)
	(crate-content crate91 medicine)
	(crate-content crate92 medicine)
	(crate-content crate93 medicine)
	(crate-content crate94 medicine)
	(crate-content crate95 medicine)
	(crate-content crate96 medicine)
	(crate-content crate97 medicine)
	(crate-content crate98 medicine)
	(crate-content crate99 medicine)
	(crate-content crate100 medicine)
	(crate-content crate101 medicine)
	(crate-content crate102 medicine)
	(crate-content crate103 medicine)
	(crate-content crate104 medicine)
	(crate-content crate105 medicine)
	(crate-content crate106 medicine)
	(crate-content crate107 medicine)
	(crate-content crate108 medicine)
	(crate-content crate109 medicine)
	(crate-content crate110 medicine)
	(crate-content crate111 medicine)
	(at person1 loc3)
	(at person2 loc46)
	(at person3 loc83)
	(at person4 loc17)
	(at person5 loc66)
	(at person6 loc54)
	(at person7 loc59)
	(at person8 loc97)
	(at person9 loc108)
	(at person10 loc91)
	(at person11 loc75)
	(at person12 loc38)
	(at person13 loc94)
	(at person14 loc58)
	(at person15 loc93)
	(at person16 loc72)
	(at person17 loc40)
	(at person18 loc29)
	(at person19 loc71)
	(at person20 loc19)
	(at person21 loc51)
	(at person22 loc77)
	(at person23 loc83)
	(at person24 loc102)
	(at person25 loc86)
	(at person26 loc17)
	(at person27 loc18)
	(at person28 loc4)
	(at person29 loc98)
	(at person30 loc93)
	(at person31 loc60)
	(at person32 loc104)
	(at person33 loc5)
	(at person34 loc17)
	(at person35 loc32)
	(at person36 loc37)
	(at person37 loc107)
	(at person38 loc109)
	(at person39 loc72)
	(at person40 loc48)
	(at person41 loc81)
	(at person42 loc4)
	(at person43 loc37)
	(at person44 loc52)
	(at person45 loc23)
	(at person46 loc38)
	(at person47 loc84)
	(at person48 loc3)
	(at person49 loc111)
	(at person50 loc107)
	(at person51 loc90)
	(at person52 loc43)
	(at person53 loc21)
	(at person54 loc22)
	(at person55 loc70)
	(at person56 loc17)
	(at person57 loc56)
	(at person58 loc15)
	(at person59 loc66)
	(at person60 loc20)
	(at person61 loc81)
	(at person62 loc19)
	(at person63 loc12)
	(at person64 loc9)
	(at person65 loc78)
	(at person66 loc73)
	(at person67 loc69)
	(at person68 loc1)
	(at person69 loc23)
	(at person70 loc94)
	(at person71 loc99)
	(at person72 loc28)
	(at person73 loc40)
	(at person74 loc38)
	(at person75 loc1)
	(at person76 loc108)
	(at person77 loc32)
	(at person78 loc56)
	(at person79 loc72)
	(at person80 loc16)
	(at person81 loc88)
	(at person82 loc60)
	(at person83 loc78)
	(at person84 loc11)
	(at person85 loc48)
	(at person86 loc101)
	(at person87 loc106)
	(at person88 loc19)
	(at person89 loc63)
	(at person90 loc88)
	(at person91 loc20)
	(at person92 loc61)
	(at person93 loc55)
	(at person94 loc90)
	(at person95 loc99)
	(at person96 loc102)
	(at person97 loc28)
	(at person98 loc75)
	(at person99 loc1)
	(at person100 loc109)
	(at person101 loc49)
	(at person102 loc24)
	(at person103 loc60)
	(at person104 loc111)
	(at person105 loc2)
	(at person106 loc6)
	(at person107 loc46)
	(at person108 loc53)
	(at person109 loc109)
	(at person110 loc72)
	(at person111 loc104)
	(person-needs person2 medicine)
	(person-needs person4 food)
	(person-needs person6 food)
	(person-needs person7 medicine)
	(person-needs person8 food)
	(person-needs person10 food)
	(person-needs person10 medicine)
	(person-needs person11 food)
	(person-needs person12 food)
	(person-needs person12 medicine)
	(person-needs person13 food)
	(person-needs person13 medicine)
	(person-needs person14 food)
	(person-needs person17 food)
	(person-needs person17 medicine)
	(person-needs person18 food)
	(person-needs person18 medicine)
	(person-needs person19 food)
	(person-needs person20 food)
	(person-needs person20 medicine)
	(person-needs person22 food)
	(person-needs person23 food)
	(person-needs person24 medicine)
	(person-needs person25 food)
	(person-needs person26 food)
	(person-needs person28 food)
	(person-needs person28 medicine)
	(person-needs person29 food)
	(person-needs person31 food)
	(person-needs person31 medicine)
	(person-needs person32 food)
	(person-needs person32 medicine)
	(person-needs person33 food)
	(person-needs person33 medicine)
	(person-needs person34 food)
	(person-needs person34 medicine)
	(person-needs person35 food)
	(person-needs person35 medicine)
	(person-needs person37 food)
	(person-needs person39 food)
	(person-needs person40 medicine)
	(person-needs person42 food)
	(person-needs person42 medicine)
	(person-needs person43 food)
	(person-needs person44 food)
	(person-needs person44 medicine)
	(person-needs person46 medicine)
	(person-needs person48 medicine)
	(person-needs person49 medicine)
	(person-needs person51 food)
	(person-needs person51 medicine)
	(person-needs person53 food)
	(person-needs person53 medicine)
	(person-needs person54 food)
	(person-needs person54 medicine)
	(person-needs person56 medicine)
	(person-needs person57 food)
	(person-needs person58 medicine)
	(person-needs person59 medicine)
	(person-needs person60 food)
	(person-needs person60 medicine)
	(person-needs person61 food)
	(person-needs person61 medicine)
	(person-needs person62 food)
	(person-needs person62 medicine)
	(person-needs person63 food)
	(person-needs person63 medicine)
	(person-needs person64 medicine)
	(person-needs person65 food)
	(person-needs person65 medicine)
	(person-needs person67 food)
	(person-needs person67 medicine)
	(person-needs person68 food)
	(person-needs person68 medicine)
	(person-needs person69 food)
	(person-needs person69 medicine)
	(person-needs person71 food)
	(person-needs person71 medicine)
	(person-needs person72 medicine)
	(person-needs person73 food)
	(person-needs person74 medicine)
	(person-needs person75 food)
	(person-needs person76 food)
	(person-needs person77 food)
	(person-needs person78 food)
	(person-needs person80 food)
	(person-needs person80 medicine)
	(person-needs person81 food)
	(person-needs person82 food)
	(person-needs person85 food)
	(person-needs person86 medicine)
	(person-needs person87 medicine)
	(person-needs person89 food)
	(person-needs person91 food)
	(person-needs person92 medicine)
	(person-needs person94 food)
	(person-needs person96 food)
	(person-needs person99 food)
	(person-needs person100 food)
	(person-needs person100 medicine)
	(person-needs person101 medicine)
	(person-needs person103 food)
	(person-needs person103 medicine)
	(person-needs person104 food)
	(person-needs person104 medicine)
	(person-needs person105 food)
	(person-needs person106 food)
	(person-needs person108 food)
	(person-needs person108 medicine)
	(person-needs person110 food)
	(person-needs person110 medicine)
)
(:goal (and
	(at drone1 depot)
	(person-has person2 medicine)
	(person-has person4 food)
	(person-has person6 food)
	(person-has person7 medicine)
	(person-has person8 food)
	(person-has person10 food)
	(person-has person10 medicine)
	(person-has person11 food)
	(person-has person12 food)
	(person-has person12 medicine)
	(person-has person13 food)
	(person-has person13 medicine)
	(person-has person14 food)
	(person-has person17 food)
	(person-has person17 medicine)
	(person-has person18 food)
	(person-has person18 medicine)
	(person-has person19 food)
	(person-has person20 food)
	(person-has person20 medicine)
	(person-has person22 food)
	(person-has person23 food)
	(person-has person24 medicine)
	(person-has person25 food)
	(person-has person26 food)
	(person-has person28 food)
	(person-has person28 medicine)
	(person-has person29 food)
	(person-has person31 food)
	(person-has person31 medicine)
	(person-has person32 food)
	(person-has person32 medicine)
	(person-has person33 food)
	(person-has person33 medicine)
	(person-has person34 food)
	(person-has person34 medicine)
	(person-has person35 food)
	(person-has person35 medicine)
	(person-has person37 food)
	(person-has person39 food)
	(person-has person40 medicine)
	(person-has person42 food)
	(person-has person42 medicine)
	(person-has person43 food)
	(person-has person44 food)
	(person-has person44 medicine)
	(person-has person46 medicine)
	(person-has person48 medicine)
	(person-has person49 medicine)
	(person-has person51 food)
	(person-has person51 medicine)
	(person-has person53 food)
	(person-has person53 medicine)
	(person-has person54 food)
	(person-has person54 medicine)
	(person-has person56 medicine)
	(person-has person57 food)
	(person-has person58 medicine)
	(person-has person59 medicine)
	(person-has person60 food)
	(person-has person60 medicine)
	(person-has person61 food)
	(person-has person61 medicine)
	(person-has person62 food)
	(person-has person62 medicine)
	(person-has person63 food)
	(person-has person63 medicine)
	(person-has person64 medicine)
	(person-has person65 food)
	(person-has person65 medicine)
	(person-has person67 food)
	(person-has person67 medicine)
	(person-has person68 food)
	(person-has person68 medicine)
	(person-has person69 food)
	(person-has person69 medicine)
	(person-has person71 food)
	(person-has person71 medicine)
	(person-has person72 medicine)
	(person-has person73 food)
	(person-has person74 medicine)
	(person-has person75 food)
	(person-has person76 food)
	(person-has person77 food)
	(person-has person78 food)
	(person-has person80 food)
	(person-has person80 medicine)
	(person-has person81 food)
	(person-has person82 food)
	(person-has person85 food)
	(person-has person86 medicine)
	(person-has person87 medicine)
	(person-has person89 food)
	(person-has person91 food)
	(person-has person92 medicine)
	(person-has person94 food)
	(person-has person96 food)
	(person-has person99 food)
	(person-has person100 food)
	(person-has person100 medicine)
	(person-has person101 medicine)
	(person-has person103 food)
	(person-has person103 medicine)
	(person-has person104 food)
	(person-has person104 medicine)
	(person-has person105 food)
	(person-has person106 food)
	(person-has person108 food)
	(person-has person108 medicine)
	(person-has person110 food)
	(person-has person110 medicine)
	))
)
