(define (problem drone_problem_d1_r0_l19_p19_c19_g19_ct2)
(:domain drone-domain)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	food - contents
	medicine - contents
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
)
(:init
	(at drone1 depot)
	(arm1-free drone1)
	(arm2-free drone1)
	(at crate1 depot)
	(at crate2 depot)
	(at crate3 depot)
	(at crate4 depot)
	(at crate5 depot)
	(at crate6 depot)
	(at crate7 depot)
	(at crate8 depot)
	(at crate9 depot)
	(at crate10 depot)
	(at crate11 depot)
	(at crate12 depot)
	(at crate13 depot)
	(at crate14 depot)
	(at crate15 depot)
	(at crate16 depot)
	(at crate17 depot)
	(at crate18 depot)
	(at crate19 depot)
	(crate-content crate1 food)
	(crate-content crate2 food)
	(crate-content crate3 food)
	(crate-content crate4 food)
	(crate-content crate5 food)
	(crate-content crate6 food)
	(crate-content crate7 medicine)
	(crate-content crate8 medicine)
	(crate-content crate9 medicine)
	(crate-content crate10 medicine)
	(crate-content crate11 medicine)
	(crate-content crate12 medicine)
	(crate-content crate13 medicine)
	(crate-content crate14 medicine)
	(crate-content crate15 medicine)
	(crate-content crate16 medicine)
	(crate-content crate17 medicine)
	(crate-content crate18 medicine)
	(crate-content crate19 medicine)
	(at person1 loc9)
	(at person2 loc17)
	(at person3 loc12)
	(at person4 loc13)
	(at person5 loc16)
	(at person6 loc19)
	(at person7 loc19)
	(at person8 loc3)
	(at person9 loc18)
	(at person10 loc15)
	(at person11 loc9)
	(at person12 loc15)
	(at person13 loc15)
	(at person14 loc16)
	(at person15 loc11)
	(at person16 loc16)
	(at person17 loc4)
	(at person18 loc11)
	(at person19 loc4)
	(person-needs person1 medicine)
	(person-needs person2 medicine)
	(person-needs person3 medicine)
	(person-needs person4 food)
	(person-needs person5 medicine)
	(person-needs person6 food)
	(person-needs person7 medicine)
	(person-needs person8 food)
	(person-needs person8 medicine)
	(person-needs person10 medicine)
	(person-needs person11 medicine)
	(person-needs person12 medicine)
	(person-needs person13 food)
	(person-needs person13 medicine)
	(person-needs person14 medicine)
	(person-needs person16 food)
	(person-needs person17 medicine)
	(person-needs person19 food)
	(person-needs person19 medicine)
)
(:goal (and
	(at drone1 depot)
	(person-has person1 medicine)
	(person-has person2 medicine)
	(person-has person3 medicine)
	(person-has person4 food)
	(person-has person5 medicine)
	(person-has person6 food)
	(person-has person7 medicine)
	(person-has person8 food)
	(person-has person8 medicine)
	(person-has person10 medicine)
	(person-has person11 medicine)
	(person-has person12 medicine)
	(person-has person13 food)
	(person-has person13 medicine)
	(person-has person14 medicine)
	(person-has person16 food)
	(person-has person17 medicine)
	(person-has person19 food)
	(person-has person19 medicine)
	))
)
