(define (problem drone_problem_d1_r0_l58_p58_c58_g58_ct2)
(:domain drone-domain)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	loc42 - location
	loc43 - location
	loc44 - location
	loc45 - location
	loc46 - location
	loc47 - location
	loc48 - location
	loc49 - location
	loc50 - location
	loc51 - location
	loc52 - location
	loc53 - location
	loc54 - location
	loc55 - location
	loc56 - location
	loc57 - location
	loc58 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	crate49 - crate
	crate50 - crate
	crate51 - crate
	crate52 - crate
	crate53 - crate
	crate54 - crate
	crate55 - crate
	crate56 - crate
	crate57 - crate
	crate58 - crate
	food - contents
	medicine - contents
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
	person42 - person
	person43 - person
	person44 - person
	person45 - person
	person46 - person
	person47 - person
	person48 - person
	person49 - person
	person50 - person
	person51 - person
	person52 - person
	person53 - person
	person54 - person
	person55 - person
	person56 - person
	person57 - person
	person58 - person
)
(:init
	(at drone1 depot)
	(arm1-free drone1)
	(arm2-free drone1)
	(at crate1 depot)
	(at crate2 depot)
	(at crate3 depot)
	(at crate4 depot)
	(at crate5 depot)
	(at crate6 depot)
	(at crate7 depot)
	(at crate8 depot)
	(at crate9 depot)
	(at crate10 depot)
	(at crate11 depot)
	(at crate12 depot)
	(at crate13 depot)
	(at crate14 depot)
	(at crate15 depot)
	(at crate16 depot)
	(at crate17 depot)
	(at crate18 depot)
	(at crate19 depot)
	(at crate20 depot)
	(at crate21 depot)
	(at crate22 depot)
	(at crate23 depot)
	(at crate24 depot)
	(at crate25 depot)
	(at crate26 depot)
	(at crate27 depot)
	(at crate28 depot)
	(at crate29 depot)
	(at crate30 depot)
	(at crate31 depot)
	(at crate32 depot)
	(at crate33 depot)
	(at crate34 depot)
	(at crate35 depot)
	(at crate36 depot)
	(at crate37 depot)
	(at crate38 depot)
	(at crate39 depot)
	(at crate40 depot)
	(at crate41 depot)
	(at crate42 depot)
	(at crate43 depot)
	(at crate44 depot)
	(at crate45 depot)
	(at crate46 depot)
	(at crate47 depot)
	(at crate48 depot)
	(at crate49 depot)
	(at crate50 depot)
	(at crate51 depot)
	(at crate52 depot)
	(at crate53 depot)
	(at crate54 depot)
	(at crate55 depot)
	(at crate56 depot)
	(at crate57 depot)
	(at crate58 depot)
	(crate-content crate1 food)
	(crate-content crate2 food)
	(crate-content crate3 food)
	(crate-content crate4 food)
	(crate-content crate5 food)
	(crate-content crate6 food)
	(crate-content crate7 food)
	(crate-content crate8 food)
	(crate-content crate9 food)
	(crate-content crate10 food)
	(crate-content crate11 food)
	(crate-content crate12 food)
	(crate-content crate13 food)
	(crate-content crate14 food)
	(crate-content crate15 food)
	(crate-content crate16 food)
	(crate-content crate17 food)
	(crate-content crate18 food)
	(crate-content crate19 food)
	(crate-content crate20 food)
	(crate-content crate21 food)
	(crate-content crate22 food)
	(crate-content crate23 food)
	(crate-content crate24 food)
	(crate-content crate25 medicine)
	(crate-content crate26 medicine)
	(crate-content crate27 medicine)
	(crate-content crate28 medicine)
	(crate-content crate29 medicine)
	(crate-content crate30 medicine)
	(crate-content crate31 medicine)
	(crate-content crate32 medicine)
	(crate-content crate33 medicine)
	(crate-content crate34 medicine)
	(crate-content crate35 medicine)
	(crate-content crate36 medicine)
	(crate-content crate37 medicine)
	(crate-content crate38 medicine)
	(crate-content crate39 medicine)
	(crate-content crate40 medicine)
	(crate-content crate41 medicine)
	(crate-content crate42 medicine)
	(crate-content crate43 medicine)
	(crate-content crate44 medicine)
	(crate-content crate45 medicine)
	(crate-content crate46 medicine)
	(crate-content crate47 medicine)
	(crate-content crate48 medicine)
	(crate-content crate49 medicine)
	(crate-content crate50 medicine)
	(crate-content crate51 medicine)
	(crate-content crate52 medicine)
	(crate-content crate53 medicine)
	(crate-content crate54 medicine)
	(crate-content crate55 medicine)
	(crate-content crate56 medicine)
	(crate-content crate57 medicine)
	(crate-content crate58 medicine)
	(at person1 loc20)
	(at person2 loc5)
	(at person3 loc39)
	(at person4 loc39)
	(at person5 loc2)
	(at person6 loc58)
	(at person7 loc10)
	(at person8 loc30)
	(at person9 loc28)
	(at person10 loc13)
	(at person11 loc1)
	(at person12 loc29)
	(at person13 loc56)
	(at person14 loc15)
	(at person15 loc9)
	(at person16 loc48)
	(at person17 loc18)
	(at person18 loc50)
	(at person19 loc58)
	(at person20 loc32)
	(at person21 loc21)
	(at person22 loc45)
	(at person23 loc21)
	(at person24 loc9)
	(at person25 loc32)
	(at person26 loc5)
	(at person27 loc51)
	(at person28 loc34)
	(at person29 loc32)
	(at person30 loc7)
	(at person31 loc9)
	(at person32 loc46)
	(at person33 loc38)
	(at person34 loc38)
	(at person35 loc42)
	(at person36 loc24)
	(at person37 loc23)
	(at person38 loc42)
	(at person39 loc29)
	(at person40 loc12)
	(at person41 loc54)
	(at person42 loc15)
	(at person43 loc8)
	(at person44 loc19)
	(at person45 loc27)
	(at person46 loc8)
	(at person47 loc1)
	(at person48 loc22)
	(at person49 loc13)
	(at person50 loc53)
	(at person51 loc29)
	(at person52 loc56)
	(at person53 loc3)
	(at person54 loc19)
	(at person55 loc16)
	(at person56 loc14)
	(at person57 loc18)
	(at person58 loc50)
	(person-needs person2 medicine)
	(person-needs person3 medicine)
	(person-needs person4 food)
	(person-needs person4 medicine)
	(person-needs person5 medicine)
	(person-needs person6 food)
	(person-needs person6 medicine)
	(person-needs person9 medicine)
	(person-needs person10 medicine)
	(person-needs person11 medicine)
	(person-needs person12 medicine)
	(person-needs person13 food)
	(person-needs person13 medicine)
	(person-needs person14 food)
	(person-needs person15 medicine)
	(person-needs person16 food)
	(person-needs person16 medicine)
	(person-needs person17 food)
	(person-needs person17 medicine)
	(person-needs person18 food)
	(person-needs person19 medicine)
	(person-needs person20 medicine)
	(person-needs person21 food)
	(person-needs person21 medicine)
	(person-needs person23 food)
	(person-needs person24 food)
	(person-needs person24 medicine)
	(person-needs person25 food)
	(person-needs person27 food)
	(person-needs person28 food)
	(person-needs person29 medicine)
	(person-needs person33 medicine)
	(person-needs person35 medicine)
	(person-needs person36 medicine)
	(person-needs person37 food)
	(person-needs person37 medicine)
	(person-needs person38 medicine)
	(person-needs person40 medicine)
	(person-needs person41 food)
	(person-needs person41 medicine)
	(person-needs person42 food)
	(person-needs person44 medicine)
	(person-needs person45 food)
	(person-needs person46 medicine)
	(person-needs person49 food)
	(person-needs person49 medicine)
	(person-needs person50 food)
	(person-needs person51 food)
	(person-needs person52 medicine)
	(person-needs person53 food)
	(person-needs person53 medicine)
	(person-needs person54 medicine)
	(person-needs person55 food)
	(person-needs person55 medicine)
	(person-needs person56 food)
	(person-needs person56 medicine)
	(person-needs person57 food)
	(person-needs person58 medicine)
)
(:goal (and
	(at drone1 depot)
	(person-has person2 medicine)
	(person-has person3 medicine)
	(person-has person4 food)
	(person-has person4 medicine)
	(person-has person5 medicine)
	(person-has person6 food)
	(person-has person6 medicine)
	(person-has person9 medicine)
	(person-has person10 medicine)
	(person-has person11 medicine)
	(person-has person12 medicine)
	(person-has person13 food)
	(person-has person13 medicine)
	(person-has person14 food)
	(person-has person15 medicine)
	(person-has person16 food)
	(person-has person16 medicine)
	(person-has person17 food)
	(person-has person17 medicine)
	(person-has person18 food)
	(person-has person19 medicine)
	(person-has person20 medicine)
	(person-has person21 food)
	(person-has person21 medicine)
	(person-has person23 food)
	(person-has person24 food)
	(person-has person24 medicine)
	(person-has person25 food)
	(person-has person27 food)
	(person-has person28 food)
	(person-has person29 medicine)
	(person-has person33 medicine)
	(person-has person35 medicine)
	(person-has person36 medicine)
	(person-has person37 food)
	(person-has person37 medicine)
	(person-has person38 medicine)
	(person-has person40 medicine)
	(person-has person41 food)
	(person-has person41 medicine)
	(person-has person42 food)
	(person-has person44 medicine)
	(person-has person45 food)
	(person-has person46 medicine)
	(person-has person49 food)
	(person-has person49 medicine)
	(person-has person50 food)
	(person-has person51 food)
	(person-has person52 medicine)
	(person-has person53 food)
	(person-has person53 medicine)
	(person-has person54 medicine)
	(person-has person55 food)
	(person-has person55 medicine)
	(person-has person56 food)
	(person-has person56 medicine)
	(person-has person57 food)
	(person-has person58 medicine)
	))
)
