(define (problem drone_problem_d1_r0_l49_p49_c49_g49_ct2)
(:domain drone-domain)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	loc42 - location
	loc43 - location
	loc44 - location
	loc45 - location
	loc46 - location
	loc47 - location
	loc48 - location
	loc49 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	crate49 - crate
	food - contents
	medicine - contents
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
	person42 - person
	person43 - person
	person44 - person
	person45 - person
	person46 - person
	person47 - person
	person48 - person
	person49 - person
)
(:init
	(at drone1 depot)
	(arm1-free drone1)
	(arm2-free drone1)
	(at crate1 depot)
	(at crate2 depot)
	(at crate3 depot)
	(at crate4 depot)
	(at crate5 depot)
	(at crate6 depot)
	(at crate7 depot)
	(at crate8 depot)
	(at crate9 depot)
	(at crate10 depot)
	(at crate11 depot)
	(at crate12 depot)
	(at crate13 depot)
	(at crate14 depot)
	(at crate15 depot)
	(at crate16 depot)
	(at crate17 depot)
	(at crate18 depot)
	(at crate19 depot)
	(at crate20 depot)
	(at crate21 depot)
	(at crate22 depot)
	(at crate23 depot)
	(at crate24 depot)
	(at crate25 depot)
	(at crate26 depot)
	(at crate27 depot)
	(at crate28 depot)
	(at crate29 depot)
	(at crate30 depot)
	(at crate31 depot)
	(at crate32 depot)
	(at crate33 depot)
	(at crate34 depot)
	(at crate35 depot)
	(at crate36 depot)
	(at crate37 depot)
	(at crate38 depot)
	(at crate39 depot)
	(at crate40 depot)
	(at crate41 depot)
	(at crate42 depot)
	(at crate43 depot)
	(at crate44 depot)
	(at crate45 depot)
	(at crate46 depot)
	(at crate47 depot)
	(at crate48 depot)
	(at crate49 depot)
	(crate-content crate1 food)
	(crate-content crate2 food)
	(crate-content crate3 food)
	(crate-content crate4 food)
	(crate-content crate5 medicine)
	(crate-content crate6 medicine)
	(crate-content crate7 medicine)
	(crate-content crate8 medicine)
	(crate-content crate9 medicine)
	(crate-content crate10 medicine)
	(crate-content crate11 medicine)
	(crate-content crate12 medicine)
	(crate-content crate13 medicine)
	(crate-content crate14 medicine)
	(crate-content crate15 medicine)
	(crate-content crate16 medicine)
	(crate-content crate17 medicine)
	(crate-content crate18 medicine)
	(crate-content crate19 medicine)
	(crate-content crate20 medicine)
	(crate-content crate21 medicine)
	(crate-content crate22 medicine)
	(crate-content crate23 medicine)
	(crate-content crate24 medicine)
	(crate-content crate25 medicine)
	(crate-content crate26 medicine)
	(crate-content crate27 medicine)
	(crate-content crate28 medicine)
	(crate-content crate29 medicine)
	(crate-content crate30 medicine)
	(crate-content crate31 medicine)
	(crate-content crate32 medicine)
	(crate-content crate33 medicine)
	(crate-content crate34 medicine)
	(crate-content crate35 medicine)
	(crate-content crate36 medicine)
	(crate-content crate37 medicine)
	(crate-content crate38 medicine)
	(crate-content crate39 medicine)
	(crate-content crate40 medicine)
	(crate-content crate41 medicine)
	(crate-content crate42 medicine)
	(crate-content crate43 medicine)
	(crate-content crate44 medicine)
	(crate-content crate45 medicine)
	(crate-content crate46 medicine)
	(crate-content crate47 medicine)
	(crate-content crate48 medicine)
	(crate-content crate49 medicine)
	(at person1 loc19)
	(at person2 loc30)
	(at person3 loc9)
	(at person4 loc49)
	(at person5 loc24)
	(at person6 loc42)
	(at person7 loc25)
	(at person8 loc46)
	(at person9 loc23)
	(at person10 loc16)
	(at person11 loc19)
	(at person12 loc36)
	(at person13 loc38)
	(at person14 loc44)
	(at person15 loc20)
	(at person16 loc47)
	(at person17 loc47)
	(at person18 loc4)
	(at person19 loc26)
	(at person20 loc13)
	(at person21 loc24)
	(at person22 loc20)
	(at person23 loc15)
	(at person24 loc6)
	(at person25 loc11)
	(at person26 loc8)
	(at person27 loc20)
	(at person28 loc41)
	(at person29 loc3)
	(at person30 loc5)
	(at person31 loc14)
	(at person32 loc1)
	(at person33 loc15)
	(at person34 loc37)
	(at person35 loc44)
	(at person36 loc46)
	(at person37 loc40)
	(at person38 loc16)
	(at person39 loc45)
	(at person40 loc16)
	(at person41 loc14)
	(at person42 loc38)
	(at person43 loc24)
	(at person44 loc2)
	(at person45 loc34)
	(at person46 loc3)
	(at person47 loc43)
	(at person48 loc46)
	(at person49 loc49)
	(person-needs person1 medicine)
	(person-needs person4 medicine)
	(person-needs person5 medicine)
	(person-needs person6 medicine)
	(person-needs person7 medicine)
	(person-needs person8 medicine)
	(person-needs person9 medicine)
	(person-needs person10 medicine)
	(person-needs person11 medicine)
	(person-needs person12 medicine)
	(person-needs person13 medicine)
	(person-needs person14 medicine)
	(person-needs person15 medicine)
	(person-needs person16 medicine)
	(person-needs person17 medicine)
	(person-needs person18 medicine)
	(person-needs person19 medicine)
	(person-needs person20 food)
	(person-needs person20 medicine)
	(person-needs person21 medicine)
	(person-needs person22 medicine)
	(person-needs person23 medicine)
	(person-needs person24 medicine)
	(person-needs person25 medicine)
	(person-needs person26 medicine)
	(person-needs person27 medicine)
	(person-needs person28 food)
	(person-needs person28 medicine)
	(person-needs person29 medicine)
	(person-needs person30 medicine)
	(person-needs person31 medicine)
	(person-needs person32 medicine)
	(person-needs person33 medicine)
	(person-needs person34 medicine)
	(person-needs person35 medicine)
	(person-needs person36 medicine)
	(person-needs person37 medicine)
	(person-needs person38 medicine)
	(person-needs person39 medicine)
	(person-needs person40 medicine)
	(person-needs person41 medicine)
	(person-needs person43 medicine)
	(person-needs person44 medicine)
	(person-needs person45 medicine)
	(person-needs person46 food)
	(person-needs person46 medicine)
	(person-needs person47 food)
	(person-needs person47 medicine)
	(person-needs person48 medicine)
)
(:goal (and
	(at drone1 depot)
	(person-has person1 medicine)
	(person-has person4 medicine)
	(person-has person5 medicine)
	(person-has person6 medicine)
	(person-has person7 medicine)
	(person-has person8 medicine)
	(person-has person9 medicine)
	(person-has person10 medicine)
	(person-has person11 medicine)
	(person-has person12 medicine)
	(person-has person13 medicine)
	(person-has person14 medicine)
	(person-has person15 medicine)
	(person-has person16 medicine)
	(person-has person17 medicine)
	(person-has person18 medicine)
	(person-has person19 medicine)
	(person-has person20 food)
	(person-has person20 medicine)
	(person-has person21 medicine)
	(person-has person22 medicine)
	(person-has person23 medicine)
	(person-has person24 medicine)
	(person-has person25 medicine)
	(person-has person26 medicine)
	(person-has person27 medicine)
	(person-has person28 food)
	(person-has person28 medicine)
	(person-has person29 medicine)
	(person-has person30 medicine)
	(person-has person31 medicine)
	(person-has person32 medicine)
	(person-has person33 medicine)
	(person-has person34 medicine)
	(person-has person35 medicine)
	(person-has person36 medicine)
	(person-has person37 medicine)
	(person-has person38 medicine)
	(person-has person39 medicine)
	(person-has person40 medicine)
	(person-has person41 medicine)
	(person-has person43 medicine)
	(person-has person44 medicine)
	(person-has person45 medicine)
	(person-has person46 food)
	(person-has person46 medicine)
	(person-has person47 food)
	(person-has person47 medicine)
	(person-has person48 medicine)
	))
)
