(define (problem drone_problem_d1_r0_l32_p32_c32_g32_ct2)
(:domain drone-domain)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	food - contents
	medicine - contents
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
)
(:init
	(at drone1 depot)
	(arm1-free drone1)
	(arm2-free drone1)
	(at crate1 depot)
	(at crate2 depot)
	(at crate3 depot)
	(at crate4 depot)
	(at crate5 depot)
	(at crate6 depot)
	(at crate7 depot)
	(at crate8 depot)
	(at crate9 depot)
	(at crate10 depot)
	(at crate11 depot)
	(at crate12 depot)
	(at crate13 depot)
	(at crate14 depot)
	(at crate15 depot)
	(at crate16 depot)
	(at crate17 depot)
	(at crate18 depot)
	(at crate19 depot)
	(at crate20 depot)
	(at crate21 depot)
	(at crate22 depot)
	(at crate23 depot)
	(at crate24 depot)
	(at crate25 depot)
	(at crate26 depot)
	(at crate27 depot)
	(at crate28 depot)
	(at crate29 depot)
	(at crate30 depot)
	(at crate31 depot)
	(at crate32 depot)
	(crate-content crate1 food)
	(crate-content crate2 food)
	(crate-content crate3 food)
	(crate-content crate4 food)
	(crate-content crate5 food)
	(crate-content crate6 food)
	(crate-content crate7 food)
	(crate-content crate8 food)
	(crate-content crate9 food)
	(crate-content crate10 food)
	(crate-content crate11 food)
	(crate-content crate12 medicine)
	(crate-content crate13 medicine)
	(crate-content crate14 medicine)
	(crate-content crate15 medicine)
	(crate-content crate16 medicine)
	(crate-content crate17 medicine)
	(crate-content crate18 medicine)
	(crate-content crate19 medicine)
	(crate-content crate20 medicine)
	(crate-content crate21 medicine)
	(crate-content crate22 medicine)
	(crate-content crate23 medicine)
	(crate-content crate24 medicine)
	(crate-content crate25 medicine)
	(crate-content crate26 medicine)
	(crate-content crate27 medicine)
	(crate-content crate28 medicine)
	(crate-content crate29 medicine)
	(crate-content crate30 medicine)
	(crate-content crate31 medicine)
	(crate-content crate32 medicine)
	(at person1 loc21)
	(at person2 loc9)
	(at person3 loc5)
	(at person4 loc29)
	(at person5 loc20)
	(at person6 loc20)
	(at person7 loc28)
	(at person8 loc16)
	(at person9 loc16)
	(at person10 loc27)
	(at person11 loc18)
	(at person12 loc29)
	(at person13 loc30)
	(at person14 loc13)
	(at person15 loc22)
	(at person16 loc24)
	(at person17 loc30)
	(at person18 loc14)
	(at person19 loc24)
	(at person20 loc25)
	(at person21 loc10)
	(at person22 loc31)
	(at person23 loc29)
	(at person24 loc3)
	(at person25 loc5)
	(at person26 loc16)
	(at person27 loc19)
	(at person28 loc5)
	(at person29 loc9)
	(at person30 loc17)
	(at person31 loc31)
	(at person32 loc2)
	(person-needs person1 medicine)
	(person-needs person2 food)
	(person-needs person2 medicine)
	(person-needs person3 medicine)
	(person-needs person4 medicine)
	(person-needs person5 medicine)
	(person-needs person6 food)
	(person-needs person6 medicine)
	(person-needs person8 medicine)
	(person-needs person9 medicine)
	(person-needs person10 food)
	(person-needs person10 medicine)
	(person-needs person11 medicine)
	(person-needs person12 medicine)
	(person-needs person14 food)
	(person-needs person15 food)
	(person-needs person15 medicine)
	(person-needs person17 medicine)
	(person-needs person18 medicine)
	(person-needs person19 food)
	(person-needs person20 medicine)
	(person-needs person21 food)
	(person-needs person22 medicine)
	(person-needs person23 medicine)
	(person-needs person24 food)
	(person-needs person25 medicine)
	(person-needs person26 medicine)
	(person-needs person27 food)
	(person-needs person29 medicine)
	(person-needs person31 food)
	(person-needs person32 food)
	(person-needs person32 medicine)
)
(:goal (and
	(at drone1 depot)
	(person-has person1 medicine)
	(person-has person2 food)
	(person-has person2 medicine)
	(person-has person3 medicine)
	(person-has person4 medicine)
	(person-has person5 medicine)
	(person-has person6 food)
	(person-has person6 medicine)
	(person-has person8 medicine)
	(person-has person9 medicine)
	(person-has person10 food)
	(person-has person10 medicine)
	(person-has person11 medicine)
	(person-has person12 medicine)
	(person-has person14 food)
	(person-has person15 food)
	(person-has person15 medicine)
	(person-has person17 medicine)
	(person-has person18 medicine)
	(person-has person19 food)
	(person-has person20 medicine)
	(person-has person21 food)
	(person-has person22 medicine)
	(person-has person23 medicine)
	(person-has person24 food)
	(person-has person25 medicine)
	(person-has person26 medicine)
	(person-has person27 food)
	(person-has person29 medicine)
	(person-has person31 food)
	(person-has person32 food)
	(person-has person32 medicine)
	))
)
