(define (problem drone_problem_d1_r0_l41_p41_c41_g41_ct2)
(:domain drone-domain)
(:objects
	drone1 - drone
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	food - contents
	medicine - contents
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
)
(:init
	(at drone1 depot)
	(arm1-free drone1)
	(arm2-free drone1)
	(at crate1 depot)
	(at crate2 depot)
	(at crate3 depot)
	(at crate4 depot)
	(at crate5 depot)
	(at crate6 depot)
	(at crate7 depot)
	(at crate8 depot)
	(at crate9 depot)
	(at crate10 depot)
	(at crate11 depot)
	(at crate12 depot)
	(at crate13 depot)
	(at crate14 depot)
	(at crate15 depot)
	(at crate16 depot)
	(at crate17 depot)
	(at crate18 depot)
	(at crate19 depot)
	(at crate20 depot)
	(at crate21 depot)
	(at crate22 depot)
	(at crate23 depot)
	(at crate24 depot)
	(at crate25 depot)
	(at crate26 depot)
	(at crate27 depot)
	(at crate28 depot)
	(at crate29 depot)
	(at crate30 depot)
	(at crate31 depot)
	(at crate32 depot)
	(at crate33 depot)
	(at crate34 depot)
	(at crate35 depot)
	(at crate36 depot)
	(at crate37 depot)
	(at crate38 depot)
	(at crate39 depot)
	(at crate40 depot)
	(at crate41 depot)
	(crate-content crate1 food)
	(crate-content crate2 food)
	(crate-content crate3 food)
	(crate-content crate4 food)
	(crate-content crate5 food)
	(crate-content crate6 food)
	(crate-content crate7 food)
	(crate-content crate8 food)
	(crate-content crate9 food)
	(crate-content crate10 food)
	(crate-content crate11 food)
	(crate-content crate12 food)
	(crate-content crate13 food)
	(crate-content crate14 food)
	(crate-content crate15 food)
	(crate-content crate16 food)
	(crate-content crate17 food)
	(crate-content crate18 food)
	(crate-content crate19 food)
	(crate-content crate20 food)
	(crate-content crate21 food)
	(crate-content crate22 food)
	(crate-content crate23 food)
	(crate-content crate24 food)
	(crate-content crate25 food)
	(crate-content crate26 food)
	(crate-content crate27 food)
	(crate-content crate28 food)
	(crate-content crate29 food)
	(crate-content crate30 food)
	(crate-content crate31 food)
	(crate-content crate32 food)
	(crate-content crate33 food)
	(crate-content crate34 food)
	(crate-content crate35 food)
	(crate-content crate36 food)
	(crate-content crate37 food)
	(crate-content crate38 food)
	(crate-content crate39 medicine)
	(crate-content crate40 medicine)
	(crate-content crate41 medicine)
	(at person1 loc12)
	(at person2 loc14)
	(at person3 loc15)
	(at person4 loc19)
	(at person5 loc40)
	(at person6 loc40)
	(at person7 loc16)
	(at person8 loc30)
	(at person9 loc11)
	(at person10 loc6)
	(at person11 loc6)
	(at person12 loc3)
	(at person13 loc1)
	(at person14 loc16)
	(at person15 loc32)
	(at person16 loc17)
	(at person17 loc35)
	(at person18 loc27)
	(at person19 loc12)
	(at person20 loc31)
	(at person21 loc13)
	(at person22 loc30)
	(at person23 loc5)
	(at person24 loc14)
	(at person25 loc37)
	(at person26 loc33)
	(at person27 loc26)
	(at person28 loc26)
	(at person29 loc24)
	(at person30 loc33)
	(at person31 loc9)
	(at person32 loc16)
	(at person33 loc20)
	(at person34 loc30)
	(at person35 loc2)
	(at person36 loc1)
	(at person37 loc29)
	(at person38 loc29)
	(at person39 loc20)
	(at person40 loc36)
	(at person41 loc41)
	(person-needs person1 food)
	(person-needs person2 food)
	(person-needs person3 food)
	(person-needs person4 food)
	(person-needs person4 medicine)
	(person-needs person6 food)
	(person-needs person7 food)
	(person-needs person8 food)
	(person-needs person9 food)
	(person-needs person10 food)
	(person-needs person11 food)
	(person-needs person12 food)
	(person-needs person13 food)
	(person-needs person14 food)
	(person-needs person15 food)
	(person-needs person16 food)
	(person-needs person16 medicine)
	(person-needs person17 food)
	(person-needs person18 medicine)
	(person-needs person19 food)
	(person-needs person20 food)
	(person-needs person21 food)
	(person-needs person22 food)
	(person-needs person23 food)
	(person-needs person24 food)
	(person-needs person25 food)
	(person-needs person26 food)
	(person-needs person27 food)
	(person-needs person28 food)
	(person-needs person30 food)
	(person-needs person31 food)
	(person-needs person32 food)
	(person-needs person33 food)
	(person-needs person34 food)
	(person-needs person35 food)
	(person-needs person36 food)
	(person-needs person37 food)
	(person-needs person38 food)
	(person-needs person39 food)
	(person-needs person40 food)
	(person-needs person41 food)
)
(:goal (and
	(at drone1 depot)
	(person-has person1 food)
	(person-has person2 food)
	(person-has person3 food)
	(person-has person4 food)
	(person-has person4 medicine)
	(person-has person6 food)
	(person-has person7 food)
	(person-has person8 food)
	(person-has person9 food)
	(person-has person10 food)
	(person-has person11 food)
	(person-has person12 food)
	(person-has person13 food)
	(person-has person14 food)
	(person-has person15 food)
	(person-has person16 food)
	(person-has person16 medicine)
	(person-has person17 food)
	(person-has person18 medicine)
	(person-has person19 food)
	(person-has person20 food)
	(person-has person21 food)
	(person-has person22 food)
	(person-has person23 food)
	(person-has person24 food)
	(person-has person25 food)
	(person-has person26 food)
	(person-has person27 food)
	(person-has person28 food)
	(person-has person30 food)
	(person-has person31 food)
	(person-has person32 food)
	(person-has person33 food)
	(person-has person34 food)
	(person-has person35 food)
	(person-has person36 food)
	(person-has person37 food)
	(person-has person38 food)
	(person-has person39 food)
	(person-has person40 food)
	(person-has person41 food)
	))
)
